home/urls.py
from django.conf.urls import url
from . import views
app_name ='home'

urlpatterns = [
    url(r'^$', views.home, name='base'),
    url(r'^home/$', views.home, name='base'),
    url(r'^base/$', views.home, name='base'),
   #url(r'^home/$', include('omk.urls')),
    url(r'^about/$', views.about, name='about'),
    url(r'^mentor/$', views.mentor, name='mentor'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^index/$', views.index, name='index'),
    url(r'^empindex/$', views.empindex, name='empindex'),
    url(r'^emphome/$', views.emphome, name='emphome'),
    url(r'^mentorhome/$', views.mentorhome, name='mentorhome'),
    url(r'^markattendance/$', views.markattendance, name='markattendance'),
    url(r'^studentsreports/$', views.studentsreports, name='studentsreports'),
    url(r'^createappointments/$', views.createappointments, name='createappointments'),
    url(r'^mentortask/$', views.mentortask, name='mentortask'),
    url(r'^empmarkattendance/$', views.empmarkattendance, name='empmarkattendance'),
    url(r'^empstudentsreports/$', views.empstudentsreports, name='empstudentsreports'),
    url(r'^empcreateappointments/$', views.empcreateappointments, name='empcreateappointments'),
    url(r'^mentorlist/$', views.mentorlist, name='mentorlist'),
    url(r'^emptask/$', views.emptask, name='emptask'),
    ]

omk/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^About Us/$', views.About_Us, name= 'About_Us'),
    url(r'', include('home.urls')),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

    ]

home/models.py
from django.db import models
from django.contrib.auth.models import Permission, User
from django.core.validators import MinLengthValidator
from django.core.validators import MaxLengthValidator
from django.core.validators import RegexValidator
from django.utils import timezone
# Create your models here.

regex=r'[0-9]'

class Employee(models.Model):
    Employee_name = models.CharField(max_length=50)
    Employee_phone = models.CharField(max_length=10, validators=[MinLengthValidator(10), RegexValidator(regex)],
                                      help_text="Phone Number should be 10 digits")
    Employee_email = models.EmailField(max_length=200)
    Employee_Address= models.CharField(max_length=200)
    Employee_Id= models.CharField(max_length=10)

    def __str__(self):
      return str(self.Employee_name)


class Mentor(models.Model):
    Mentor_email = models.EmailField(max_length=49, default='X@gmail.com')
    Mentor_name = models.CharField(max_length=49)
    Mentor_phone = models.CharField(max_length=10, validators=[MinLengthValidator(10), RegexValidator(regex)],
                                    help_text="Phone Number should be 10 digits")
    Mentor_Address=models.CharField(max_length=200)
    Mentor_Gender=models.CharField(max_length=10, default ='X' ,help_text="Enter F or M")
    Mentor_Id=models.CharField(max_length=10)
#    student_count = models.IntegerField(max_digits=10) (we should do the hardcode in later sprint)

    def __str__(self):
       return str(self.Mentor_name)

class Student(models.Model):
     Student_id= models.CharField(max_length=15)
     Student_name=models.CharField(max_length=49)
     Student_email = models.EmailField(max_length=25, default='X@gmail.com')
     Student_grade = models.CharField(max_length=10)
     Parents_email = models.EmailField(max_length=200, default='X@gmail.com')
     Parents_phone = models.CharField(validators=[MinLengthValidator(10), RegexValidator(regex)], max_length=10)
     School= models.CharField(max_length=49)
     Men_name =models.ForeignKey(Mentor,related_name='Menemail')
     Emp_name= models.ForeignKey(Employee, related_name='Empemail')
     created_date = models.DateTimeField(default=timezone.now)

     def created(self):
         self.created_date = timezone.now()
         self.save()

     def __str__(self):
      return str(self.Men_name)

     def __str__(self):
       return str(self.Emp_name)

class Appointment(models.Model):
    Sname = models.ForeignKey(Student, related_name='Appointment')
    Mname = models.ForeignKey(Mentor, related_name='Appointment')
    Sid = models.ForeignKey(Student, related_name='Appointment2')


    def __str__(self):
        return str(self.sname)

home/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Employee, Mentor, Student

class EmployeeForm(forms.ModelForm):
    class Meta:
         model = Employee
         fields = ('Employee_name','Employee_phone','Employee_Address', 'Employee_Id' )



class MentorForm(forms.ModelForm):
    class Meta:
         model = Mentor
         fields = ('Mentor_name','Mentor_phone','Mentor_Address' ,'Mentor_Gender' ,'Mentor_Id')

class StudentForm(forms.ModelForm):
    class Meta:
         model = Student
         fields = ('Student_id','Student_name','Student_email','Student_grade',
                   'Parents_email','Parents_phone','School','Men_name','Emp_name',)

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password',]

home/views.py
from django.shortcuts import render

# Create your views here.


from django.utils import timezone
from .models import *
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from .forms import *
from django.db.models import *
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout



def home(request):
    return render(request, 'home/base.html',
                  {'home': home})

def about(request):
    return render(request, 'home/about.html',
                  {'about': about})


def mentor(request):
    return render(request, 'home/mentor.html',
                  {'mentor': mentor})

def index(request):
    return render(request, 'home/index.html',
                  {'index': index})

def empindex(request):
    return render(request, 'home/empindex.html',
                  {'empindex': empindex})

def emphome(request):
    return render(request, 'home/emphome.html',
                  {'emphome': emphome})

def mentorhome(request):
    return render(request, 'home/mentorhome.html',
                  {'mentorhome': mentorhome})

def markattendance(request):
    return render(request, 'home/markattendance.html',
                  {'markattendance': markattendance})

def studentsreports(request):
    return render(request, 'home/studentsreports.html',
                  {'studentsreports': studentsreports})

def createappointments(request):
    return render(request, 'home/createappointments.html',
                  {'createappointments': createappointments})

def mentortask(request):
    return render(request, 'home/mentortask.html',
                  {'mentortask': mentortask})

def empmarkattendance(request):
    return render(request, 'home/empmarkattendance.html',
                  {'empmarkattendance': empmarkattendance})

def empstudentsreports(request):
    return render(request, 'home/empstudentsreports.html',
                  {'empstudentsreports': empstudentsreports})

def empcreateappointments(request):
    return render(request, 'home/empcreateappointments.html',
                  {'empcreateappointments': empcreateappointments})

def emptask(request):
    return render(request, 'home/emptask.html',
                  {'emptask': emptask})

def mentorlist(request):
    return render(request, 'home/mentorlist.html',
                  {'mentorlist': mentorlist})

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'home/base.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_staff:
                login(request, user)
                return render(request, 'home/emphome.html')
            else:
                login(request, user)
                return render(request, 'home/mentorhome.html')
        else:
            return render(request, 'home/login.html', {'error_message': 'Invalid login'})
    return render(request, 'home/login.html')

def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'home/login.html')
    context = {
        "form": form,
    }
    return render(request, 'home/register.html', context)

def password_reset(request):
    return render(request, 'home/password_reset.html',
    {'home': password_reset})


def password_reset_confirm(request):
    return render(request, 'home/password_reset_confirm.html',
    {'home': password_reset_confirm})

def password_reset_email(request):
    return render(request, 'home/password_reset_email.html',
    {'home': password_reset_email})

def password_reset_complete(request):
    return render(request, 'home/password_reset_complete.html',
    {'home': password_reset_complete})

def Student_list(request):
    Student_list = Student.objects.filter(created_date__lte=timezone.now())
    return render(request, 'home/mentorhome.html',
    {'home': Student_list})

home/templates/home/about.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>OMAHA MENTOR FOR KIDS</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
  </head>
  <body>
    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <header class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">OMK</h3>
              <nav class="nav nav-masthead">
                <a class="nav-link active" href="{% url 'home:base' %}">Home</a>
                <a class="nav-link" href="{% url 'home:about' %}">About Us</a>
                <a class="nav-link" href="{% url 'home:login_user' %}">Login</a>
              </nav>
            </div>
          </header>
          <h1> Omaha Mentor for Kids is a non profit organization that helps in guiding students to stay focused on studies.</h1>



             <footer class="mastfoot">
            <div class="inner">
              <p>Contact Us at  <a href="omkidsorg@gmail.com">omkidsorg@gmail.com </a>.</p>
            </div>
          </footer>

        </div>
      </div>

    </div>

  </body>

home/templates/home/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>OMAHA MENTOR FOR KIDS</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <header class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">OMK</h3>
              <nav class="nav nav-masthead">
                <a class="nav-link active" href="#">Home</a>
                <a class="nav-link" href="{% url 'home:about' %}">About Us</a>
                <a class="nav-link" href="{% url 'home:login_user' %}">Login</a>
              </nav>
            </div>
          </header>

            <main role="main" class="inner cover">
  <h1 class="cover-heading">OMAHA MENTOR FOR KIDS</h1>
  <p class="lead"></p>
  <p class="lead">
    <a href="{% url 'home:about' %}" class="btn btn-lg btn-secondary">Learn more</a>
  </p>
</main>


            <footer class="mastfoot">
            <div class="inner">
              <p>Contact Us at  <a href="omkidsorg@gmail.com">omkidsorg@gmail.com </a>.</p>
            </div>
          </footer>

        </div>

      </div>
      {% block body %}
      {% endblock %}
    </div>

  </body>
</html>

home/templates/home/base_visitor.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>OMAHA MENTOR FOR KIDS</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <header class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">OMK</h3>
              <nav class="nav nav-masthead">
                <a class="nav-link active" href="{% url 'home:base' %}">Home</a>
                <a class="nav-link" href="{% url 'home:about' %}">About Us</a>
                <a class="nav-link" href="{% url 'home:login_user' %}">Login</a>
              </nav>
            </div>
          </header>



              {% block body %}
              {% endblock %}
            </div>


        </div>

      </div>

    </div>

  </body>
</html>

home/templates/home/createappointments.html
{% extends 'home/index.html' %}
{% block content %}

<p> This is create appointments Page</p>
{% endblock %}

home/templates/home/empindex.html
{% load staticfiles %}

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.1/moment.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css"/>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"> -->
  <!--<link href="{% static 'css/style.css' %}" rel="stylesheet">-->
  <!--<link rel="stylesheet" type="text/css" href="style.css"> -->
  <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
  <!-- Page level plugin CSS-->
  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">

  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript">
              $( function() {
                  $("#datetimepicker1").datetimepicker();
              });
</script>
  <script type="text/javascript">
        $(function () {
            $('#datetimepicker12').datetimepicker({
                inline: true,
                sideBySide: true
            });
        });
    </script>
</head>
<body >
{% if user.is_authenticated %}
<div id="wrapper">
  <!-- Navigation-->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home:emphome' %}">Omaha Mentor for Kids</a>
            </div>

    <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Hello {{user.username}} <b class="caret"></b></a>
                    <ul class="dropdown-menu">

                        <li class="divider"></li>
                        <li>
                            <a href="{% url 'home:logout_user' %}"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
            </ul>

    <!--SideBar Start-->

    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav side-nav">

        <li>
            <a href="{% url 'home:empmarkattendance' %}"><i class="fa fa-fw fa-check-square-o"></i> Mark Attendance</a>
        </li>
        <li>
          <a  href="{% url 'home:empstudentsreports' %}"><i class="fa fa-fw fa-table"></i>Students Reports</a>
        </li>
        <li>
          <a  href="{% url 'home:empcreateappointments' %}"><i class="fa fa-fw fa-calendar"></i>Create Appointments</a>
        </li>

        <li>
          <a   href="{% url 'home:emphome' %}"><i class="fa fa-fw fa-home"></i>Home</a>
        </li>
        <li>
          <a href="{% url 'home:emptask' %}"><i class="fa fa-fw fa-tasks"></i>Task</a>
        </li>
        <li>
          <a href="{% url 'home:mentorlist' %}"><i class="fa fa-fw fa-tasks"></i>Mentor List</a>
        </li>

      </ul>
    </div>
  </nav>
  <div id="page-wrapper">

    <div class="container-fluid">
    {% block content %}
    {% endblock %}
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Core plugin JavaScript-->
    <script src="{% static 'js/plugins/morris/raphael.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>

  </div>
{% endif %}
</div>
</body>

</html>

home/templates/home/empmarkattendance.html
{% extends 'home/empindex.html' %}
{% block content %}

<p> This is Employee mark attendance Page</p>
<div class="container-fluid">

<div>

        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Grade</th>
                  <th>Attendance</th>
                </tr>
              </thead>
              <tbody>
              <tr> <td>
                        <label class="switch">
                        <input type="checkbox">
                        <span class="slider round"></span>
                        </label>
                  </td></tr>
              {% for Student_list in home %}
                <tr>
                  <td>{{ Student_list.Student_name }}</td>
                  <td>{{ Student_list.Student_grade }}</td>
                  <td>
                        <label class="switch">
                        <input id="toggle-slider_position()" type="checkbox">
                        <span class="slider round"></span>
                        </label>
                  </td>
                </tr>
              {% endfor %}
              </tbody>

            </table>



          </div>
            <br/>
            <div class="row" >
                <div class="col-sm-4"></div>
                             <div class='col-sm-4' align="center">
                                <div class="form-group">
                                    <div class='input-group date' id='datetimepicker1'>
                                        <input type='text' class="form-control" />
                                        <span class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                                    </div>
                                </div>
                                 <button class="btn btn-lg">Submit</button>
                            </div>
                             <div class="col-sm-4">


                                 </div>
                        </div>
            <br/><br/><br/><br/><br/>
        </div>

      </div>
</div>
{% endblock %}

home/templates/home/empstudentsreports.html
{% extends 'home/empindex.html' %}
{% block content %}

<p> This is Employee students reports Page</p>
{% endblock %}

home/templates/home/emptask.html
{% extends 'home/empindex.html' %}
{% block content %}

<p> This is Employee Task Page</p>
{% endblock %}

home/templates/home/login.html
{% extends 'home/baselogin.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'home:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    <a href="{% url 'password_reset' %}"> Reset Password</a> here.
                </div>

            </div>
        </div>
    </div>

</div>

{% endblock %}

home/templates/home/mentor.html
{% load staticfiles %}
<div class="row"  align="center">
    <div id="rcorners1" class="col-md-3">
        <!-- Text input-->
        <div class="form-group">
              <label class="col-md-6 control-label" for="fn">Email Id</label>
              <div class="col-md-6">
              <input id="fn" name="fn" type="text" placeholder="Email id" class="form-control input-md" required="">
          </div>
        </div>
        <div class="form-group">
              <label class="col-md-6 control-label" for="fn">Password</label>
              <div class="col-md-6">
              <input id="fn" name="fn" type="text" placeholder="Password" class="form-control input-md" required="">
          </div>
        </div>
        <br/>
        <!-- Button -->
        <div class="form-group">
          <label class="col-md-6 control-label" for="submit"></label>
          <div class="col-md-6">
            <button id="submit" name="submit" class="btn btn-primary">SIGN IN</button>
          </div>
        </div>
        <div class="form-group">
          <label class="col-md-5 control-label" for="submit"></label>
          <div class="col-md-7">
            <a href="">Reset Password</a>
          </div>
        </div>
    </div>
    <div class="col-md-3"></div>
     <div id="rcorners2" class="col-md-6">
        <!-- Text input-->
        <div class="form-group">
              <label class="col-md-6 control-label" for="fn">Name</label>
              <div class="col-md-6">
              <input id="fn" name="fn" type="text" placeholder="Name" class="form-control input-md" required="">
          </div>
        </div>
        <div class="form-group">
              <label class="col-md-6 control-label" for="fn">E-mail</label>
              <div class="col-md-6">
              <input id="fn" name="fn" type="text" placeholder="E-mail" class="form-control input-md" required="">
          </div>
        </div>
         <div class="form-group">
              <label class="col-md-6 control-label" for="fn">Password</label>
              <div class="col-md-6">
              <input id="fn" name="fn" type="text" placeholder="Password" class="form-control input-md" required="">
          </div>
        </div>
         <div class="form-group">
              <label class="col-md-6 control-label" for="fn">Confirm Password</label>
              <div class="col-md-6">
              <input id="fn" name="fn" type="text" placeholder="Confirm Password" class="form-control input-md" required="">
          </div>
        </div>
         <div class="form-group">
              <label class="col-md-6 control-label" for="fn">Designation</label>
              <div class="col-md-6">
              <input id="fn" name="fn" type="text" placeholder="Designation" class="form-control input-md" required="">
          </div>
        </div>

            <br/>
        <!-- Button -->
        <div class="form-group">
          <label class="col-md-6 control-label" for="submit"></label>
          <div class="col-md-6">
            <button id="submit" name="submit" class="btn btn-primary">SIGN IN</button>
          </div>
        </div>
    </div>
</div>

home/templates/home/mentorhome.html
{% extends 'home/index.html' %}
{% block content %}

<p> This is Mentor Home Page</p>
<div class="align-middle">

  <form class="form-wrapper" style="text-align: center;">
  <h3>Search Students here</h3>
  <input type="text" id="search" placeholder="Search for..." required>
  <input type="submit" value="Go" id="submit">
  </form>
 </div>

<div>
<table class="table table-striped table-bordered table-hover">
<thead>
<tr class="bg-info">
<th>Student ID</th>
<th>Student Name</th>
<th>Student Grade</th>
<th>Student School Name</th>
</tr>
</thead>
<tbody>
{% for Student_list in home %}
<tr>
<td>{{ Student_list.Student_id }}</td>
<td>{{ Student_list.Student_name }}</td>
<td>{{ Student_list.Student_grade }}</td>
<td>{{ Student_list.School }}</td>

</tr>
{% endfor %}
</tbody>
</table>
</div>
{% endblock %}

home/templates/home/mentorlist.html
{% extends 'home/empindex.html' %}
{% block content %}

<p> This is Mentor List Page</p>
{% endblock %}

home/templates/home/register.html
{% extends 'home/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'home/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'home:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

home/templates/home/studentsreports.html
{% extends 'home/index.html' %}
{% block content %}

<p> This is students reports Page</p>
{% endblock %}